# Sử dụng Python 3.10 làm base image
FROM python:3.10-slim

# Thiết lập thư mục làm việc bên trong container
WORKDIR /app

# Cài đặt các dependencies cần thiết cho hệ điều hành
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Sao chép file requirements.txt vào container
COPY requirements.txt /app/

# Cài đặt các Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Sao chép mã nguồn của dự án vào container
COPY . /app/

# Mở port 8000 để truy cập ứng dụng Django
EXPOSE 8000

# Lệnh khởi chạy container
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
