# Generated by Django 5.1.3 on 2024-11-15 02:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TWO_IMG2IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_3d_input', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('img_style_input', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
            ],
        ),
    ]
