# Generated by Django 5.1.3 on 2024-11-16 10:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TWO_IMG2IMG_WITH_PROMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_3d_input', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('img_style_input', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('promt_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
