# Generated by Django 5.1.3 on 2024-12-05 04:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_two_img2img_with_promt"),
    ]

    operations = [
        migrations.CreateModel(
            name="MASK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img_mask_input",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.upload_to
                    ),
                ),
                (
                    "img_material_input",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.upload_to
                    ),
                ),
            ],
        ),
    ]
