# Generated by Django 5.1.3 on 2024-12-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_mask"),
    ]

    operations = [
        migrations.AddField(
            model_name="mask",
            name="ipadapter",
            field=models.FloatField(default=0.8),
        ),
    ]
