# Generated by Django 5.1.3 on 2024-12-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_mask_ipadapter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mask",
            old_name="ipadapter",
            new_name="ipadapter_weight",
        ),
    ]
